services:
  postgres: # postgres는 사용자 지정 서비스 명. 
    image: postgres:16 # 이미지 받아오기 (공식)
    container_name: webrtc-postgres # 컨테이너 이름 정해주기 (컨테이너 여러개 쓰면 2개 이상 늘리기 어려워서 안쓰는게 나음)
    restart: unless-stopped # 사용자가 멈춘거 아니면 자동 다시시작
    ports:
      - "127.0.0.1:${DB_PORT}:5432" # [내 컴퓨터포트]:[컨테이너 포트]
    environment: # docker mapping 방식
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data # named volume 방식으로 괜히 마운팅했다가 파일 깨지는거 막기
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # 상태 확인용 명령어: CMD-SHELL(컨테이너의 쉘)을 이용해서 pg_isready 명령어(postgresql 공식 명령어)로 확인하기
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s # 검사 주기 
      timeout: 5s # 검사 시 타임아웃 시간
      retries: 5 # 5번 연속 실패하면 unhealthy 처리

# 볼륨을 named로 설정하여 영구 저장되게 하기
volumes:
  postgres_data: